#import math
#angulo = float(input('Digite um ângulo: '))
#tangente = math.tan(math.radians(angulo))
#cosseno = math.cos(math.radians(angulo))
#seno = math.sin(math.radians(angulo))
#print('Seno: {:.2f}'.format(seno))
#print('Cosseno: {:.2f}'.format(cosseno))
#print('Tangente: {:.2f}'.format(tangente))
#import math
#ângulo = float(input('Digite o ângulo que você deseja: '))
#seno = math.sin(math.radians(ângulo))
#print('O ângulo de {} tem o SENO de {:.2f}.'.format(ângulo, seno))
#cosseno = math.cos(math.radians(ângulo))
#print('O ângulo de {} tem o COSSENO de {:.2f}.'.format(ângulo, cosseno))
#tangente = math.tan(math.radians(ângulo))
#print('O ângulo de {} tem a TANGENTE de {:.2f}.'.format(ângulo, tangente))
from math import radians, sin, cos, tan

ângulo = float(input('Digite o ângulo que você deseja: '))
seno = sin(radians(ângulo))
print('O ângulo de {} tem o SENO de {:.2f}.'.format(ângulo, seno))
cosseno = cos(radians(ângulo))
print('O ângulo de {} tem o COSSENO de {:.2f}.'.format(ângulo, cosseno))
tangente = tan(radians(ângulo))
print('O ângulo de {} tem a TANGENTE de {:.2f}.'.format(ângulo, tangente))
