frase = str(input('Digite uma frase: ')).lower()
a = frase.count('a')
print('A letra a aparece {} vezes.'.format(a))
posicao = frase.find('a')
print('E ela aparece pela primeira vez na {} posição.'.format(posicao + 1))
posicao = frase.rfind('a')
print('E ela aparece pela ultima vez na {} posição.'.format(posicao + 1))