frase = str(input('Digite uma frase: ')).strip().lower()
cont = frase.count('a')
print(f'A letra [a] aparece {cont} vezes.')
print(f'Ela aparece pela primeira vez na {frase.find("a") + 1} posição.')
print(f'A ultima vez que ela aparece é na {frase.rfind("a") + 1} posição.')