variavel = input('Digite alguma coisa: ')

print('É um titulo: {}'.format(variavel.istitle()))
print('É um numero: {}'.format(variavel.isnumeric()))
print('Esta em caixa alta: {}'.format(variavel.isupper()))
print('Esta em caixa baixa: {}'.format(variavel.islower()))
print('São apenas letras: {}'.format(variavel.isalpha()))
print('São digitos: {}'.format(variavel.isdigit()))
print('É decimal: {}'.format(variavel.isdecimal()))
print('É ASCII: {}'.format(variavel.isascii()))
print('É um num: {}'.format(variavel.isalnum()))
print('É um identificador: {}'.format(variavel.isidentifier()))
print('É um printable: {}'.format(variavel.isprintable()))
print('É um espaço: {}'.format(variavel.isspace()))