inteiro = int(input('Digite um numero inteiro: '))

print('{} x {} = {}'.format(inteiro, 1, inteiro * 1))
print('{} x {} = {}'.format(inteiro, 2, inteiro * 2))
print('{} x {} = {}'.format(inteiro, 3, inteiro * 3))
print('{} x {} = {}'.format(inteiro, 4, inteiro * 4))
print('{} x {} = {}'.format(inteiro, 5, inteiro * 5))
print('{} x {} = {}'.format(inteiro, 6, inteiro * 6))
print('{} x {} = {}'.format(inteiro, 7, inteiro * 7))
print('{} x {} = {}'.format(inteiro, 8, inteiro * 8))
print('{} x {} = {}'.format(inteiro, 9, inteiro * 9))
print('{} x {} = {}'.format(inteiro, 10, inteiro * 10))
