numero_inteiro = int(input('Digite um numero inteiro: '))

print(f'{numero_inteiro} x 1 = {numero_inteiro * 1}')
print(f'{numero_inteiro} x 2 = {numero_inteiro * 2}')
print(f'{numero_inteiro} x 3 = {numero_inteiro * 3}')
print(f'{numero_inteiro} x 4 = {numero_inteiro * 4}')
print(f'{numero_inteiro} x 5 = {numero_inteiro * 5}')
print(f'{numero_inteiro} x 6 = {numero_inteiro * 6}')
print(f'{numero_inteiro} x 7 = {numero_inteiro * 7}')
print(f'{numero_inteiro} x 8 = {numero_inteiro * 8}')
print(f'{numero_inteiro} x 9 = {numero_inteiro * 9}')
print(f'{numero_inteiro} x 10 = {numero_inteiro * 10}')